---
# tasks file for logrotate
- name: Setup Log Rotate
  ansible.builtin.include_tasks:
    file: logrotate-install.yml
    apply:
      tags:
        - logrotate-install
        - all
        - logrotate
      become: true
  tags:
    - logrotate-install
    - all
    - logrotate
    - never

- name: Purge Log Rotate
  ansible.builtin.include_tasks:
    file: logrotate-purge.yml
    apply:
      tags:
        - logrotate-purge
        - purge
      become: true
  tags:
    - logrotate-purge
    - purge
    - never

- name: Cleanup Log Rotate
  ansible.builtin.include_tasks:
    file: logrotate-clean.yml
    apply:
      tags:
        - logrotate-install
        - logrotate-clean
        - logrotate
        - all
  tags:
    - logrotate-install
    - logrotate-clean
    - logrotate
    - all
    - never
